### ISSUE TITLE
Array of tables fail

### ISSUE THREAD

**Issue by belka-ew** [dlang-community/toml#5]
```toml
[[override]]
a = 30

[override.symbols]
"S.f" = 30

[[override]]
a = 40

[override.symbols]
"S.f" = 25
```

Parsing this file fails with:

> toml.toml.TOMLParserException@../../../.dub/packages/toml-2.0.1/toml/src/toml/toml.d(599): Table name has already been directly defined (10:18)
