### ISSUE TITLE
TOML file that ends with comment crashes

### ISSUE THREAD

**Issue by katastic** [dlang-community/toml#7]
```TOML
[data]
    pygmentize = '2' # if we don't do our own

```
works fine (has newline after comment)

```TOML
[data]
    pygmentize = '2' # if we don't do our own
```
crashes with off-by-one error. (github inserts a newline there, there is no newline on the second example after comment)
```D
toml\src\toml\toml.d(1007): index [328] is out of bounds for array of length 328
```

code here:
```D
void readKeyValue(string[] keys) {
      if (clear()) {
         enforceParser(data[index++] == '=', "Expected '=' after key declaration");
         if (clear!false()) {
            set(keys, readValue());
            // there must be nothing after the key/value declaration except comments and whitespaces
            if (clear!false())
1007:           enforceParser(data[index] == '\n', "Invalid characters after value declaration: " ~ data[index]);
```
